[package]
name = "AviScript"
version = "0.1.0"
edition = "2021"

[dependencies]
rhai = { version = "*", features = ["debugging", "decimal", "serde" ] }
uuid = { version = "*", features = ["v4"] }
rhai-fs = "*"
rhai-url = "*"